courses/urls.py
from django.urls import path
from courses import views

urlpatterns = [
    # Categories ========
    path("category_list/<slug:slug>", views.category_view, name="categories"),
    # Courses ========
    path("course_detail/<slug:slug>", views.category_detail_view, name="lesson_detail"),
    path("like/<int:course_id>/", views.like_course, name="like"),
    path("courses/<slug:course_id>/", views.course_detail_view, name="course_detail"
    ),  # Course details and modules
    path("course/<slug:course_id>/enroll/", views.student_enroll_course, name="student_enroll_course",),  # Enroll in a course
    # ===========
    # Lesson
    path("courses/<slug:course_id>/lessons/<slug:lesson_id>",views.lesson_detail_view, name="lesson_detail",),  # Course details and modules
    #  Module
    path("modules/<int:module_id>/courses/", views.module_courses, name="module_courses"),
    # path( "module/<slug:public_id>/", views.module_detail, name="module_detail"),  # Topics in a module
    
    path('get-content/<int:course_id>/', views.get_content, name='get_content'),



]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/', include('accounts.urls')),
    path('courses/', include('courses.urls')),
    path('instructors/', include('instructors.urls')),
    path('payments/', include('payment.urls')),


    path('profiles/', include('profiles.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile/<username>', views.profile_view, name='profile'),
    path('certificate/<slug:public_id>', views.StudentCertificatesView.as_view(), name='user_certificate'),
    path('student-notification/<slug:public_id>', views.StudentNotificationView.as_view(), name='student_notification'),
    path('courses/<slug:public_id>', views.StudentCoursesView.as_view(), name='student_courses'),


]

courses/models.py
from datetime import timedelta, timezone
import uuid
from django.db import models
from django.utils.text import slugify
from cloudinary.models import CloudinaryField
from courses.fields import OrderField
import helpers
from django.core.validators import FileExtensionValidator
import cloudinary.uploader

helpers.cloudinary_init()

def generate_public_id(instance, title=None):
    """Generate a unique public ID for uploaded files."""
    unique_id = str(uuid.uuid4()).replace("-", "")
    if title:
        slug = slugify(title)
        return f"{slug}-{unique_id[:32]}"
    return unique_id

def get_public_id_prefix(instance):
    """Generate public ID prefix based on the instance's class and existing public ID."""
    path = getattr(instance, 'path', None) or ''
    path = path.strip("/")
    public_id = instance.public_id or ''
    model_name = slugify(instance.__class__.__name__)
    return f"{model_name}/{public_id}" if public_id else model_name

def get_display_name(instance):
    """Return the display name for the instance."""
    return getattr(instance, 'get_display_name', lambda: instance.title)()

# Base model for common attributes
class BaseContent(models.Model):
    title = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    public_id = models.CharField(max_length=130, blank=True, null=True, db_index=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.public_id:
            self.public_id = generate_public_id(self, self.title)
        if self.title:
            self.title = self.title.title() 
        super().save(*args, **kwargs)

class Category(BaseContent):
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["created_at"]

    def __str__(self):
        return self.title

class Subject(BaseContent):
    category = models.ForeignKey(Category, related_name="subjects", on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    author = models.ForeignKey("accounts.customUser", on_delete=models.CASCADE, related_name="subjects_author")

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

class AccessRequirement(models.TextChoices):
    ANYONE = "any", "Anyone"
    EMAIL_REQUIRED = "email", "Email required"

class PublishStatus(models.TextChoices):
    PUBLISHED = "publish", "Published"
    COMING_SOON = "soon", "Coming Soon"
    DRAFT = "draft", "Draft"

class Course(BaseContent):
    instructor = models.ForeignKey('instructors.Instructor', on_delete=models.CASCADE, related_name="courses_instructure", blank=True, null=True)
    owner = models.ForeignKey("accounts.customUser", on_delete=models.CASCADE, related_name="courses_created", blank=True, null=True)
    subject = models.ForeignKey(Subject, related_name="subject_courses", on_delete=models.CASCADE, null=True, blank=True)
    students = models.ManyToManyField("accounts.customUser", related_name="courses_joined", blank=True)
    description = models.TextField(blank=True, null=True)
    pdf = models.OneToOneField("File", on_delete=models.CASCADE, null=True, blank=True)
    
    image = CloudinaryField(
        "image", 
        null=True, 
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,
        tags=["course", "thumbnail"]
    )
    
    access = models.CharField(max_length=10, choices=AccessRequirement.choices, default=AccessRequirement.EMAIL_REQUIRED, null=True, blank=True)
    status = models.CharField(max_length=10, choices=PublishStatus.choices, default=PublishStatus.DRAFT, null=True, blank=True)
    is_free = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    likes = models.IntegerField(default=0)
    liked_by = models.ManyToManyField("accounts.customUser", through="Likes", related_name="liked_courses", blank=True)
    
    total_ratings = models.PositiveIntegerField(default=0)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

    @property
    def is_published(self):
        return self.status == PublishStatus.PUBLISHED

class CourseMetrics(models.Model):
    course = models.OneToOneField(Course, on_delete=models.CASCADE, related_name='metrics')
    total_views = models.PositiveIntegerField(default=0)
    total_likes = models.PositiveIntegerField(default=0)
    total_comments = models.PositiveIntegerField(default=0)
    total_downloads = models.PositiveIntegerField(default=0)
    total_enrollments = models.PositiveIntegerField(default=0)
    total_dislikes = models.PositiveIntegerField(default=0)

class Likes(models.Model):
    user = models.ForeignKey("accounts.customUser", on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="course_likes")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "course")
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.user.username} likes {self.course.title}"

class Module(models.Model):
    course = models.ForeignKey(Course, related_name="modules", on_delete=models.CASCADE, blank=True, null=True)
    public_id = models.CharField(max_length=130, blank=True, null=True, db_index=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    order = OrderField(blank=True, for_fields=["course"])
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Course: {self.course} -- Module: {self.title}"

    def save(self, *args, **kwargs):
        if not self.public_id:
            self.public_id = generate_public_id(self, self.title)
        super().save(*args, **kwargs)

class Lesson(models.Model):
    title = models.CharField(max_length=255)
    public_id = models.CharField(max_length=130, blank=True, null=True, db_index=True)
    description = models.TextField(blank=True, null=True)
    module = models.ForeignKey(Module, related_name="lessons", on_delete=models.CASCADE)
    order = OrderField(blank=True, for_fields=["module"])
    
    thumbnail = CloudinaryField("image", 
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,
        tags=['thumbnail', 'lesson'],
        blank=True, null=True
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if not self.public_id:
            self.public_id = generate_public_id(self, self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Lesson: {self.title} - Module: {self.module.title}'

class LessonVideo(models.Model):
    public_id = models.CharField(max_length=130, blank=True, null=True, db_index=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name="videos")
    duration = models.DurationField(blank=True, null=True)
    
    video = CloudinaryField("video", 
        public_id_prefix=get_public_id_prefix,
        display_name=get_display_name,                
        blank=True, null=True, type='private',
        tags=['video', 'lesson'], resource_type='video'
    )
    
    url = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if not self.public_id:
            self.public_id = generate_public_id(self, self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} - Lesson: {self.lesson.title}"

class File(models.Model):
    pdf_file = models.FileField(upload_to="lesson/pdf")

class Student(models.Model):
    public_id = models.CharField(max_length=130, blank=True, null=True, db_index=True)
    user = models.OneToOneField("accounts.customUser", on_delete=models.CASCADE, related_name="students")
    enrolled_courses = models.ManyToManyField(Course, through="Enrollment")

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if not self.public_id:
            self.public_id = generate_public_id(self.user.username) 
        super().save(*args, **kwargs)

class EnrollmentStatus(models.TextChoices):
    PENDING = ("pending", "Pending")
    COMPLETED = ("completed", "Completed")
    CANCELLED = ("cancelled", "Cancelled")

class Enrollment(models.Model):
    public_id = models.CharField(max_length=130, blank=True, null=True, db_index=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name="enrollments")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="enrollments")
    enrollment_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=EnrollmentStatus.choices, default=EnrollmentStatus.PENDING)
    enrolled_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("student", "course")

    def __str__(self):
        return f"{self.student.user.username} enrolled in {self.course.title}"
    def save(self, *args, **kwargs):
        if not self.public_id:
            self.public_id = generate_public_id(self, self.student.user.username)
        super().save(*args, **kwargs)
class Quiz(models.Model):
    title = models.CharField(max_length=250)
    module = models.ForeignKey(Module, related_name="quizzes", on_delete=models.CASCADE, blank=True, null=True)
    public_id = models.CharField(max_length=130, blank=True, null=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:

profiles/forms.py
from django import forms

from profiles.models import ProfileUser


class ProfileForms(forms.ModelForm):
    class Meta:
        model = ProfileUser
        fields = ['user', 'full_name', 'bio', 'profile_picture']

profiles/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views import generic
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from courses.models import Course, Enrollment, Notification, Student
from instructors.models import Certificate
from io import BytesIO
from django.core.files import File
from instructors.models import Certificate
from profiles.models import ProfileUser
from .forms import ProfileForms
from django.contrib.auth.decorators import login_required


@login_required
def profile_view(request, username):
    # Retrieve the user or return a 404 if not found
    user = get_object_or_404(ProfileUser, user__username=username)
    print(user)
    # Process form data on POST request
    if request.method == 'POST':
        form = ProfileForms(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form_instance = form.save(commit=False)
            form_instance.user = request.user
            form_instance.save()  # Save the form with the user instance
            return redirect('profile', username=request.user.username)  # Redirect after successful form submission
    else:
        form = ProfileForms(instance=user)  # Pre-fill the form with the user's data

    # Context to be passed to the template
    context = {
        'user': user,
        'form': form,  # Include the form in the context
    }

    return render(request, 'profile/profile.html', context)
@login_required
def certificate_view(request, public_id):
    certificate = get_object_or_404(Certificate, student__user__public_id=public_id)
    return render(request, 'profile/certificate.html', {'certificate': certificate})



class StudentCertificatesView(LoginRequiredMixin, generic.ListView):
    template_name = 'profile/certificate.html'
    model = Certificate
    slug_field = 'public_id'
    slug_url_kwarg = 'public_id'
    def get_queryset(self):
        return super().get_queryset().filter(student__user=self.request.user)
    


class StudentNotificationView(LoginRequiredMixin, generic.DetailView):
    template_name = 'students/notification.html'
    model = Notification
    slug_field = 'public_id'
    slug_url_kwarg = 'public_id'
    def get_queryset(self):
        return super().get_queryset().filter(student=self.request.user)
    
    def get(self, request, *args, **kwargs):
        """
        Override the get method to mark the notification as read
        when it's accessed by the student.
        """
        # Mark the notification as read
        notification = self.get_object()  # Get the specific notification object
        if not notification.is_read:
            notification.is_read = True
            notification.save()
        return super().get(request, *args, **kwargs)

    

class StudentCoursesView(LoginRequiredMixin, generic.ListView):
    template_name = 'students/student_courses.html'
    model = Course
    context_object_name = 'enrolled_courses'


    
    def get_queryset(self):
        # Get the list of courses that the student is enrolled in
        student = Student.objects.get(user=self.request.user)
        enrolled_courses = Course.objects.filter(enrollments__student=student)
        return enrolled_courses

profiles/templates/profile/certificate.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Home Page
{% endblock title %}

{% block content %}

{% for certificate in object_list %}

<div class="container mx-auto py-8">
    <div class="container mx-auto py-10">
        <div class="max-w-lg mx-auto bg-white shadow-lg rounded-lg p-6">
          <h1 class="text-2xl font-bold text-gray-800 mb-4">{{ certificate.course.title }} Certificate</h1>
          <p class="text-gray-600">Student: {{ certificate.student.user.username }}</p>
          <p class="text-gray-600 mb-4">Awarded on: {{ certificate.date_awarded|date:"F d, Y" }}</p>
              
          <!-- Display certificate file -->
          <div class="mt-6">
            <embed src="{{ certificate.certificate_file.url }}"  type="application/pdf" class="w-full h-64 border" />
          </div>
    
          <!-- Download Button -->
          <div class="mt-6 text-center">
            <a href="{{ certificate.certificate_file.url }}" download class="hover-download inline-block px-4 py-2 bg-green-500 text-white text-sm font-medium rounded hover:bg-green-600">
                Download Certificate
              </a>
              
          </div>
        </div>
      </div>
        <!-- jQuery action: Show a message when the button is clicked -->
        {% endfor %}
       
       <script>
          $(document).ready(function() {
    $(".hover-download").hover(
        function() {
            $(this).addClass("bg-green-700");
        },
        function() {
            $(this).removeClass("bg-green-700");
        }
    );
});

        </script>
    </div>
</div>

{% endblock %}

profiles/templates/profile/certificate_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Certificate</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white">
    <div class="max-w-lg mx-auto border-4 border-gray-800 p-10 bg-white text-center shadow-xl">
        <h1 class="text-4xl font-bold text-gray-800 mb-4">Certificate of Completion</h1>
        <p class="text-xl text-gray-600 mb-8">This is to certify that</p>
        <h2 class="text-3xl font-semibold text-gray-900">{{ student.user.get_full_name }}</h2>
        <p class="text-xl text-gray-600 mt-4">has successfully completed the</p>
        <h3 class="text-2xl font-semibold text-gray-900">{{ course.title }}</h3>
        <p class="text-xl text-gray-600 mt-8">Awarded on: {{ certificate.date_awarded|date:"F d, Y" }}</p>

        <div class="mt-12">
            <p class="text-sm text-gray-500">Authorized by</p>
            <p class="text-lg font-semibold text-gray-800">Your Organization Name</p>
        </div>
    </div>
</body>
</html>

profiles/templates/profile/profile.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Home Page
{% endblock title %}

{% block content %}


    <div class="max-w-4xl mx-auto mt-10 mb-10 p-6 bg-white shadow-md rounded-lg">
        <!-- Profile Header -->
         
        
            
        <div class="flex items-center">
            {% if user.profile_picture %}
            <img src="{{ user.profile_picture.url }}" alt="{{ user.user.username }}" class="w-20 h-20 rounded-full">
            
            {% else %}
            <img src="{% static 'img/no_image.png' %}" alt="{{ user.user.username }}" class="w-20 h-20 rounded-full">

            {% endif %}
            <div class="ml-4 px-4">
                <h2 class="text-2xl font-semibold">{{ user.user.username }}</h2>
              
            </div>
        </div>

        <!-- Profile Form -->
        <div class="mt-6">
            <h3 class="text-xl font-semibold mb-4">Edit Profile</h3>

            <form method="POST" enctype="multipart/form-data" class="space-y-4">
                {% csrf_token %}

                <!-- Username (Read-Only) -->
                <div>
                    <label class="block text-sm font-medium text-gray-700">Username</label>
                    <input type="text" value="{{ user.user.username }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm bg-gray-100 ">
                </div>
                <!-- Full_Name (Read-Only) -->
                <div>
                    <label class="block text-sm font-medium text-gray-700">Full Name</label>
                    <input type="text" value="{{ form.full_name.value }}" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm bg-gray-100 ">
                </div>
                <!-- Bio -->
                <div>
                    <label for="bio" class="block text-sm font-medium text-gray-700">Bio</label>
                    <textarea id="bio" name="bio" rows="3" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">{{ form.bio.value }}</textarea>
                </div>

                <!-- Profile Picture -->
                <div>
                    <label for="profile_picture" class="block text-sm font-medium text-gray-700">Profile Picture</label>
                    <input id="profile_picture" name="profile_picture" type="file" class="mt-1 block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50">
                    <p class="mt-2 text-sm text-gray-500">Upload a new profile picture.</p>
                </div>
                  <!-- Course Enrollments -->
               <div class="w-full shadow border rounded-md mt-3 mb-3 p-4">
                        

                   {% if request.user.students %}
                   {% for enrollment in request.user.students.enrollment_set.all %}
                   <ol>
                 <li class="flex p-1 ">
                    <span class="px-3">

                        {{ forloop.counter }}
                    </span>
                     <div class="flex items-center">
                       <h3 class="text-sm font-medium">{{ enrollment.course.instructor.user.username }}</h3>
                       
                             <p class="text-sm text-gray-100 px-1">{{ enrollment.course.title }}</p>
                         </div>
                         
                     <div class="flex items-center">
                         <span class="text-sm text-gray-500"> Enrolled On: {{ enrollment.date_enrolled|timesince }}</span>
                     </div>
                    
                     
                 </li>

                </ol>
                     {% endfor %}
                     {% else %}
                     <p class="mt-2 text-sm text-gray-500">You are not enrolled in any courses.</p>
                     {% endif %}
                         
                    
                 </div>
             
                <!-- Submit Button -->
                <div>
                    <button type="submit" class="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700">
                        Save Changes
                    </button>
                </div>
            </form>
             
        </div></div>
        </div>
    </div>

{% endblock content %}